import {
  RequestBodyBase,
  ResponseBase
} from '../../common/request-response.type';

export interface ProductNearblyStoreBody extends RequestBodyBase {
  codigoTienda: number;
  eanArticulo: string;
  latitud: number;
  longitud: number;
}

// Generated by https://quicktype.io

export interface ProductNearblyStoreRes {
  dato: Dato;
}

export interface ProductNearblyStoreResponse extends ResponseBase {
  data: ProductNearblyStoreRes;
}
export interface Dato {
  listaArticulo: { [key: string]: null | string }[];
  listaTalla: any[];
  listaColor: any[];
  listaInventario: ListaInventario[];
  listaEAN: any[];
}

export interface ListaInventario {
  cod_Tienda: string;
  descripcion: string;
  ean: string;
  cantidad: string;
  art_Con: string;
}
