// Generated by https://quicktype.io

export interface AddressResponse {
  cellphoneNumber: string;
  cellphonePreffix: string;
  country: Country;
  defaultAddress: boolean;
  firstName: string;
  id: string;
  line1: string;
  line2: string;
  otherInfo: string;
  phone: string;
  region: Country;
  town: string;
}

export interface Country {
  isocode: string;
}
