// Generated by https://quicktype.io

import { RequestBodyBase, ResponseBase } from '../common/request-response.type';

export interface NotificationListRes {
  id: number;
  title: string;
  shortDescription: string;
  content: string;
  timestamp: string;
}

export interface NotificationListResponse extends ResponseBase {
  data: {
    unread: number;
    notifications: NotificationListRes[];
  };
}
export interface deletedNotificationBody extends RequestBodyBase {
  id: number;
}
export interface NotificationDeletedResponse extends ResponseBase {
  data: number;
}
export interface NotificationDetailResponse extends ResponseBase {
  data: {
    content: string;
  };
}

export interface NotificationDetailBody extends RequestBodyBase {
  id: number;
}
