export * from './Barcode';
export * from './CategoryPage';
export * from './ErrorPage';
//export * from './ProductPage'
export * from './RecoveryPass';
//export * from './Search'
//export * from './SignIn'
export * from './SignUp';
export * from './Splash/SplashScreen';
export * from './Stories';
export * from './Welcome/WelcomeScreen';
export * from './dashboard/PDP/PDPScreen';
export * from './dashboard/PLP/PLPScreen';
export * from './home';
export * from './contactless-payment';
