require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
$RNFirebaseAsStaticFramework = true
$RNFirebaseAnalyticsWithoutAdIdSupport = true

target 'AppV2' do
  config = use_native_modules!
  rn_maps_path = '../node_modules/react-native-maps'
  rn_facebook_path = '../node_modules/react-native-fbsdk-next'
  permissions_path = '../node_modules/react-native-permissions'
  permissions_ios_path = "#{permissions_path}/ios"
  camera_permissions_path = '../node_modules/react-native-permissions/ios/Camera.podspec'

  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'react-native-fbsdk-next', :path => rn_facebook_path
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'RNPermissions', :path => permissions_path
  pod 'Permission-Camera', :path => "#{permissions_ios_path}/Camera"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_ios_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_ios_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_ios_path}/LocationWhenInUse"
  pod 'Permission-FaceID', :path => "#{permissions_ios_path}/FaceID"

  pod 'GoogleSignIn', '~> 6.1.0'
  pod 'FBSDKLoginKit'

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'Firebase/Messaging', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'RNFBAnalytics', :path => '../node_modules/@react-native-firebase/analytics'
  pod 'GoogleIDFASupport', '~> 3.14.0'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  target 'AppV2Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == 'react-native-config'
          config.build_settings['ENVFILE'] = '$(PODS_ROOT)/../../.env'
        end
      end
    end
  end
end