// Generated by https://quicktype.io

import { ResponseBase } from '../common/request-response.type';

export interface CountriesResponse {
  countries: Response[];
}

export interface Response {
  isocode: string;
  name: string;
}

export interface RegionsResponse {
  regions: Response[];
}

export interface CitiesResponse {
  regions: Response[];
}

export interface MapDataResponse {
  label: string;
  value: string;
}
